### PR TITLE
icon: use xml icon for xsl

### PR DESCRIPTION
**Pull request by minad**

### CODE REVIEW

**Comment by Alexander-Miller** [comment]
We had some conflicts, so I used the github web tool to resolve them. Now we have two commits and more conflicts. Well done, github, well done.

Please resolve and squash, and we'll get this merged as well.

**Comment by minad** [comment]
done

**Comment by Alexander-Miller** [comment]
> This branch has conflicts that must be resolved

Now it's back to the original conflict. My guess is you need to rebase your branch against master to make this work.

**Comment by minad** [comment]
ops, I actually forgot to do the rebase

**Comment by Alexander-Miller** [comment]
:+1:

**Pull request merged**
