### PR TITLE
 Compatibility with perspective.el

### LINKED ISSUE #687: perspective.el vs persp-mode for Treemacs-persp
Hi, I'm interested in using perspective.el for frame management. I see it has a name clash with persp-mode for some functions. 

Will this affect treemacs-persp? I see you explicitly require persp-mode package. Is there a reason to choose one over the other? 

Thanks!

### PR DESCRIPTION
**Pull request by jkdufair**
Closes #687

### CODE REVIEW

**Comment by Alexander-Miller** [comment]
Everything looks in order on a first impression. However I'm going to keep this on the back burner for a couple of days - I still have a few TODOs noted down for the persp module that I'd like to finish first. ETA: some time next week.

**Comment by Alexander-Miller** [comment]
After a thorough review the opportunity for clean ups did not materialize after all, so we're good to merge now.

:+1:

**Comment by jsmestad** [comment]
@Alexander-Miller does `treemacs-perspective` need to get pushed to MELPA?

**Comment by Alexander-Miller** [comment]
Oops.

It's here now: https://github.com/melpa/melpa/pull/7211

**Pull request merged**
