### PR TITLE
[FIX] remove `-S` flag from python status call

### PR DESCRIPTION
**Pull request by mpanarin**
Connected to the issue https://github.com/Alexander-Miller/treemacs/issues/453

I noticed that I have this issue only inside virtualenvironments created with `virtualenvwrapper`, this fixes the issue.

### CODE REVIEW

**Comment by Alexander-Miller** [comment]
You should remove the other instances of its use as well. It's all in the same file.

Even if that is not strictly necessary, I'd prefer things be consistent,

**Comment by Alexander-Miller** [comment]
Oh and let's start the commit message with `[Misc]`.

**Comment by mpanarin** [comment]
@Alexander-Miller done

**Comment by Alexander-Miller** [comment]
:+1:

**Pull request merged**
