### PR TITLE
Add java and kotlin icons

### PR DESCRIPTION
**Pull request by ram535**
Add java and kotlin icons

### CODE REVIEW

**Comment by Alexander-Miller** [comment]
Can you brighten up java's cup? It's difficult to see on a dark background: https://imgur.com/PBiR6ZA. Giving the cup a solid background is probably easiest. 

And don't mind travis, it's just acting up: 

>  (file-notify-error "Could not add watch for file" "No space left on device" "/home/travis/build/Alexander-Miller/treemacs/test")

**Comment by Alexander-Miller** [comment]
Bump?

**Comment by ram535** [comment]
is white color okay?

**Comment by Alexander-Miller** [comment]
The border is a bit heavy. I rounded the edges here https://imgur.com/a/AwnP1
Use that image and squash the commits and we're good to go.

**Comment by Alexander-Miller** [comment]
You are probably picking the wrong commits. When you select a commit for squashing it is merged into the one above it in the list, so you cannot pick the first. See here: https://stackoverflow.com/questions/39595034/git-cannot-squash-without-a-previous-commit-error-while-rebase

When you are done squashing you will then need to push with --force since your local and remote commit histories will have diverged.

Magit also has a much nicer interface for that sort of thing than the bare command line.

**Comment by ram535** [comment]
I hope I did correctly. I used magit because I couldn't figure it out how to do it in the command line.

**Comment by Alexander-Miller** [comment]
Looks good :+1:

**Pull request merged**
