### PR TITLE
open file on double click

### PR DESCRIPTION
**Pull request by wyuenho**
Currently double clicking on a file in treemacs will only attempt to open the file's tags. If no tags are found, there's no way to visit a file with a mouse click. This PR fixes it.

### CODE REVIEW

**Comment by Alexander-Miller** [comment]
As per the discussion in https://github.com/Alexander-Miller/treemacs/issues/79 most people wanted to go the other way: click = open file, double-click = expand content


Your solution will also not work correctly since the mouse1 function is called with both a single and double click. In general a double-click is not supposed to do more than a single click, but that's not what we're doing in treemacs, so make this work clicks would have to work with timers.

**Comment by wyuenho** [comment]
If anything this change is inconsistent, since the "open" action is done using both a single click and a double click, but this actually will work. The double click action is debounced by emacs already, you are not going to receive 2 single and 1 double.

**Comment by wyuenho** [comment]
I can make this configurable if you want.

**Comment by wyuenho** [comment]
Closing this, I'm gonna try something different. tab/enter/mouse-click are just too weird in treemacs now.

**Pull request closed without merging**
