### PR TITLE
[all-the-icons] Changed org-mode icon to the org unicorn in all-the-icons theme

### PR DESCRIPTION
**Pull request by jeslie0**
There is an org icon in all-the-icons and we should use it for the all-the-icons-theme. This change removes org from using the `all-the-icons-octicon "file-text"` icon and makes it now use `all-the-icons-fileicon "org"`, with a light green face.

### CODE REVIEW

**Comment by Alexander-Miller** [comment]
LGTM. Prefix the commit message with `[all-the-icons]` and we're good to go.

**Comment by jeslie0** [comment]
Okay, I believe I have done that now!

**Comment by Alexander-Miller** [comment]
You changed the title of the PR in github. It's copied from the commit message, but they are independent things. To change the commit message you have to amend you commit and force push it again.

I took care of that stuff, so we can merge here.

**Comment by Alexander-Miller** [comment]
Aaand I forgot to actually push my changes before pushing the button. Never mind, nothing a little `--force` can't solve.

**Pull request merged**
