### PR TITLE
[Git] Improve Git script performance

### LINKED ISSUE #379: Spacemacs: Git mode causes 100 % CPU usage by treemacs-git-status.py
Opening treemacs `v2.5-2019.03.03 @ 26.1` causes 100 % CPU churn on 2 cores. I've tried setting
```
  (setq-default treemacs-git-mode nil)
  (setq-default treemacs-use-git-mode nil)
  (setq-default treemacs-use-follow-mode nil)
  (fset #'trace-follow-hook #'ignore)
```
in `dotspacemacs/user-config` and also 
```
 '(treemacs-git-mode nil)
 '(treemacs-follow-mode nil)
```
in `dotspacemacs/emacs-custom-settings` but both git-mode and follow mode gets automatically enabled
causing 100 % churn by `treemacs-git-status.py`.

### PR DESCRIPTION
**Pull request by Jasu**
This builds on #403.

Currently, `treemacs-git-status.py` concatenates output into a string. This makes Python do a lot of GC freeing the previous string, and spend most of its time in the `brk` syscall reallocating the heap.

This PR makes the script build the output into a list, and only `join` it at the very end.

Before the change building a hash table of 22204 entries took 8 seconds and 20418 `brk`s, after it takes 317 milliseconds and 19 `brk`s. The output was identical in my test case (containing both Git status changes and a recursive scan over an expanded directory).

Very likely fixes #379.

### CODE REVIEW

**Comment by Alexander-Miller** [comment]
It wasn't even that long ago that I got curious about just that issue and looked up whether python has something like a StringBuffer, but SO told me that it's really not that different from straight up concatenation. I guess that's not true outside of simple for loops.

Let's fix those conflicts and I'll merge. I am also curious: what kind of tools do you use to profile a python script like this?

**Comment by Jasu** [comment]
I rebased this on master.

I used `strace`, i.e. just `strace python ...`, it shows syscalls made by Python like this:

```
stat("/home/jasu/.emacs.d/treemacs/icons/asdf", 0x7ffc7cc50ae0) = -1 ELOOP (Too many levels of symbolic links)
stat("/home/jasu/.emacs.d/treemacs/lg", {st_mode=S_IFREG|0644, st_size=7644306, ...}) = 0
stat("/home/jasu/.emacs.d/treemacs/lgw", {st_mode=S_IFREG|0644, st_size=6825052, ...}) = 0
stat("/home/jasu/.emacs.d/treemacs/src/elisp/backtrace", {st_mode=S_IFREG|0644, st_size=32076, ...}) = 0
stat("/home/jasu/.emacs.d/treemacs/src/elisp/treemacs-evil.el", {st_mode=S_IFREG|0644, st_size=3642, ...}) = 0
read(3, "s-git-status.py\n?? src/elisp/tre"..., 100) = 100
stat("/home/jasu/.emacs.d/treemacs/src/elisp/treemacs-git-status.py", {st_mode=S_IFREG|0644, st_size=2940, ...}) = 0
stat("/home/jasu/.emacs.d/treemacs/src/elisp/treemacs-icons-dired.el", {st_mode=S_IFREG|0644, st_size=6374, ...}) = 0
stat("/home/jasu/.emacs.d/treemacs/src/elisp/treemacs-projectile.el", {st_mode=S_IFREG|0644, st_size=4284, ...}) = 0
read(3, "\n?? \"\\302\\250\"\n!! .cask/\n!! src/"..., 100) = 100
```

I initially suspected that it would stat the same files million times over for some reason, but the output showed a huge amount of `brk` syscalls, indicating that it performed lots of heap allocations.

`strace` is one of my favorite debugging tools, below are the most common ways I use it:

* `sudo strace -p SOMEPID` - attach `strace` to a running process
* `strace -e trace=%file COMMAND` - trace only file syscalls
* `strace -T COMMAND` - include time spent in syscalls after each call. Often I do the following to get a time-sorted list: `strace -T COMMAND 2>strace.out` `sed 's/\(.*\) <\(.*\)>/\2 \1/' strace.out|sort -n`
* `strace -f COMMAND` - follows into forked processes, useful for tracing e.g. shell scripts

When attaching to an existing process, I use `lsof` or `ls -l /proc/PID/fd/` to find out what the file descriptor numbers are referring to.

**Comment by Jasu** [comment]
Rebased on `master`.

**Comment by Alexander-Miller** [comment]
:+1: and thanks for the strace explanation.

**Pull request merged**
