### PR TITLE
[Git] Fix directory face override project face.

### PR DESCRIPTION
**Pull request by BlindingDark**
Before:
image

After:
image

### CODE REVIEW

**Comment by Alexander-Miller** [comment]
This fix should not be needed. A change in a file should lead to a re-highlight of all its parents up to, but *excluding*, the root. So this is treating the symptom, but not the cause, of the problem.

I've run into this bug as well, but most of the time things work as intended and I have yet to narrow down what's causing it. Do you have a recipe to more or less reliably reproduce this?

**Comment by BlindingDark** [comment]
@Alexander-Miller 
> reliably reproduce

```shell
emacs -q
```
```elisp
(treemacs-git-mode 'deferred)
```

1. Create a new git repository.
1. Add a new file to the **root** of the project.
1. **Commit!**
1. Modify this file and save it.

image


I noticed that if git state of the file has not changed, it will not reproduce.
So, for example, commit and then modify will trigger this bug.

**Comment by Alexander-Miller** [comment]
Ah, looks like the setup code is wrong when the file is directly under the root. I'll look into this.

**Comment by Alexander-Miller** [comment]
I'll be fixing this as part of everything that comes with #558.

**Pull request closed without merging**
